docker-compose.yml, market/market.go
=> Change markets provider priority and docker-compose

services/assets/info.go, services/assets/info_test.go
=> Change GetCoinInfo and add test for it

market/charts.go
Reverts trustwallet/watchmarket#58
=> Revert "Change charts provider to coingecko"

api/marketdata.go
Maybe prematurely optimized given the performance of the other APIs is much slower but why not ;)
* Changes fully covered by existing tests
* Ran Newman tests
=> Speeds up /v1/market/tickers API

api/marketdata.go
Reverts trustwallet/watchmarket#64
=> Revert "Speeds up /v1/market/tickers API"

storage/market.go, storage/market_test.go
Prematurely optimized but why not ;)
=> Speeds up `Save Rates`

storage/market.go, storage/market_test.go
Reverts trustwallet/watchmarket#68
=> Revert "Speeds up `Save Rates`"

market/ticker/cmc/cmc.go, market/ticker/cmc/cmc_test.go, storage/market.go
Fixes https://github.com/trustwallet/android/issues/2889
=> Checksum cmc token_id before save to Redis

services/markets/coinmarketcap/mapping.go
added BEP20 tokens
CREAM
ATOM
ZEC
YFII
=> adding BEP20 tokens 09-16

services/markets/coinmarketcap/mapping.go
adding ANKR BEP20
https://bscscan.com/token/0xf307910a4c7bbc79691fd374889b36d8531b08e3
https://coinmarketcap.com/currencies/ankr/
=> adding ANKR BEP20

services/markets/coinmarketcap/mapping.go
adding SUN TRC20 token
https://coinmarketcap.com/currencies/sun/
=> adding SUN TRC20

services/markets/coinmarketcap/mapping.go
adding BURGER
https://coinmarketcap.com/currencies/burger-swap/
=> adding BURGER BEP20

services/markets/coinmarketcap/mapping.go
adding PancakeSwap CAKE token
https://coinmarketcap.com/currencies/pancakeswap/
=> adding CAKE BEP20

services/markets/coinmarketcap/mapping.go
adding TRC20 SEED
https://medium.com/sesameseedorg/key-points-2aa8c02a440a
TRC20 SEED will be replacing TRC10 SEED
Did not remove TRC10 SEED yet
=> adding TRC20 SEED

services/markets/coinmarketcap/mapping.go
adding BEP20 TWT
https://bscscan.com/address/0x4b0f1812e5df2a09796481ff14017e6005508003
price from https://coinmarketcap.com/currencies/trust-wallet-token/
=> adding BEP20 TWT

services/markets/coinmarketcap/mapping.go
adding JUL that is both on ERC20 and BEP20
https://coinmarketcap.com/currencies/justliquidity/
=> adding BEP20/ERC20 JUL

services/markets/coinmarketcap/mapping.go
Due to the recent Kucoin hack, UTK team is doing a token swap.
Old contract:
0x70a72833d6bf7f508c8224ce59ea1ef3d0ea3a38
New contract:
0xdc9ac3c20d1ed0b540df9b1fedc10039df13f99c
=> modify ERC20 UTK

services/markets/coinmarketcap/mapping.go
changed token contract for ERC20 VIDT
added token contract for BEP20 VIDT
https://coinmarketcap.com/currencies/vidt-datalink/
=> updating ERC20 and adding BEP20 VIDT

services/markets/coinmarketcap/mapping.go
Adding token price for Venus Protocol
https://coinmarketcap.com/currencies/venus/
=> adding BEP20 XVS

services/markets/coinmarketcap/mapping.go
adding CORE
https://etherscan.io/token/0x62359ed7505efc61ff1d56fef82158ccaffa23d7
https://coinmarketcap.com/currencies/cvault-finance/
=> adding ERC20 CORE

services/markets/coinmarketcap/mapping.go
adding Bidao (BID)
https://coinmarketcap.com/currencies/bidao/
=> adding ERC20 BID

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/alpha-finance-lab
https://bscscan.com/token/0xa1faa113cbe53436df28ff0aee54275c13b40975
=> adding BEP20 ALPHA

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/yfedfinance/
https://etherscan.io/token/0x2DBd330bC9B7f3A822a9173aB52172BdDDcAcE2A
=> adding ERC20 YFED

services/markets/coinmarketcap/mapping.go
https://medium.com/kardiachain/kardiachain-issues-1-1-token-swap-in-response-to-kucoin-security-breach-ensuring-no-loss-to-kai-218b564b03d7
old token:
https://etherscan.io/token/0xbd6467a31899590474ce1e84f70594c53d628e46
new token:
https://etherscan.io/token/0xd9ec3ff1f8be459bb9369b4e79e9ebcf7141c093
=> modify ERC20 KAI

services/markets/coinmarketcap/mapping.go
https://twitter.com/NoiaNetwork/status/1310508271732547584
https://coinmarketcap.com/currencies/noia-network/
removed: https://etherscan.io/token/0xfc858154c0b2c4a3323046fb505811f110ebda57
new contract: https://etherscan.io/token/0xa8c8CfB141A3bB59FEA1E2ea6B79b5ECBCD7b6ca
=> modify ERC20 NOIA

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/fee-active-collateral-token/
https://etherscan.io/token/0x23aEfF664c1B2bbA98422a0399586e96cc8a1C92
=> adding ERC20 FACT

services/markets/coinmarketcap/mapping.go
https://medium.com/fetch-ai/announcing-the-fet-token-swap-3eef3d272f73
https://coinmarketcap.com/currencies/fetch/
old contract: https://etherscan.io/token/0x1d287cc25dad7ccaf76a26bc660c5f7c8e2a05bd
new contract: https://etherscan.io/token/0xaea46A60368A7bD060eec7DF8CBa43b7EF41Ad85
=> modify ERC20 FET

services/markets/coinmarketcap/mapping.go
adding the following BEP20 tokens:
NEAR: https://bscscan.com/token/0x1fa4a73a3f0133f0025378af00236f3abdee5d63
FIL: https://bscscan.com/token/0x0d8ce2a99bb6e3b7db580ed848240e4a0f9ae153
BAT: https://bscscan.com/token/0x101d82428437127bf1608f699cd651e6abf9766e
AVA: https://bscscan.com/token/0x13616f44ba82d63c8c0dc3ff843d36a8ec1c05a9
SXP: https://bscscan.com/token/0x47bead2563dcbf3bf2c9407fea4dc236faba485a
SNX: https://bscscan.com/token/0x9Ac983826058b8a9C7Aa1C9171441191232E8404
UNI: https://bscscan.com/token/0xBf5140A22578168FD562DCcF235E5D43A02ce9B1
YFI: https://bscscan.com/token/0x88f1A5ae2A3BF98AEAF342D26B30a79438c9142e
Source:
https://www.binance.com/en/support/announcement/c7e2b4f39fa549ed812d825adbc6e210
=> adding BEP20 10-16

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/bakerytoken/
https://bscscan.com/token/0xE02dF9e3e622DeBdD69fb838bB799E3F168902c5
=> Add BAKE BEP20 10-18-2020

services/markets/coinmarketcap/mapping.go
https://medium.com/@presearch/presearch-token-swap-complete-9a454d976a52
old token: https://etherscan.io/token/0x88a3e4f35d64aad41a6d4030ac9afe4356cb84fa
new token: https://etherscan.io/token/0xEC213F83defB583af3A000B1c0ada660b1902A0F
=> modify ERC20 PRE

services/markets/coinmarketcap/mapping.go
adding INJ ERC20 and BEP20
https://research.binance.com/en/projects/injective-protocol
https://etherscan.io/token/0xe28b3b32b6c345a34ff64674606124dd5aceca30
https://bscscan.com/token/0xa2b726b1145a4773f68593cf171187d8ebe4d495
=> add ERC20 and BEP20 INJ

services/markets/coinmarketcap/mapping.go
adding BEP20
KAVA: https://bscscan.com/token/0x5f88ab06e8dfe89df127b2430bba4af600866035
USDX: https://bscscan.com/token/0x1203355742e76875154c0d13eb81dcd7711dc7d9
=> adding BEP20 KAVA and USDX

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/earneo/
https://explorer.binance.org/asset/RNO-14E
=> adding BEP2 RNO

services/markets/coinmarketcap/mapping.go
adding CTK https://research.binance.com/en/projects/certik
https://coinmarketcap.com/currencies/certik/
https://bscscan.com/token/0xA8c2B8eec3d368C0253ad3dae65a5F2BBB89c929
=> add BEP20 CTK

services/markets/coinmarketcap/mapping.go
add BEP20 PAX
https://bscscan.com/token/0xb7f8cd00c5a06c0537e2abff0b58033d02e5e094
=> add BEP20 PAX

services/markets/coinmarketcap/mapping.go
adding TLB
https://coinmarketcap.com/currencies/the-luxury-coin/
=> add ERC20 TLB

services/markets/coinmarketcap/mapping.go
https://medium.com/@pancakeswap/urgent-action-required-changes-to-syrup-pools-70b98d7b2541
=> remove BEP20 SYRUP

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/tatcoin/
https://coinmarketcap.com/currencies/chonk/
=> add ERC20 TAT CHONK

services/markets/coinmarketcap/mapping.go
Change the price feed from https://coinmarketcap.com/currencies/bitcoin-bep2 to https://coinmarketcap.com/currencies/bitcoin/
=> edit BEP20 BTCB

services/markets/coinmarketcap/mapping.go
adding 
https://coinmarketcap.com/currencies/yearn-classic-finance
https://etherscan.io/token/0x63a18BC38D1101DB7F0efCbCBdCbe927A5879039
=> add ERC20 EARN

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/hard-protocol/
https://bscscan.com/token/0xf79037f6f6be66832de4e7516be52826bc3cbcc4
=> add BEP20 HARD

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/amp/
https://etherscan.io/token/0xff20817765cb7f73d4bde2e66e067e58d11095c2
=> add ERC20 AMP

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/dogdeficoin/
https://etherscan.io/token/0x80bb277f4355A43CDbB86a82F9876C946476d9Eb
=> add ERC20 DOGDEFI

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/bridge-oracle/markets/
https://tronscan.org/#/token20/TJvqNiWUN2v2NBG12UhfV7WSvReJkRP3VC
=> add TRC20 BRG

services/markets/coinmarketcap/mapping.go
adding BEP2 ADA price
https://coinmarketcap.com/currencies/cardano/
=> add BEP2 ADA

services/markets/coinmarketcap/mapping.go
https://www.kucoin.com/news/en-capp-pivx-olt-deposits-and-withdrawals-now-open
https://coinmarketcap.com/currencies/cappasity/
old contract: https://etherscan.io/token/0x04f2e7221fdb1b52a68169b25793e51478ff0329
new contract: https://etherscan.io/token/0x11613b1f840bb5A40F8866d857e24DA126B79D73
=> edit ERC20 CAPP

services/markets/coinmarketcap/mapping.go
adding https://coinmarketcap.com/currencies/swirge/
https://etherscan.io/token/0x92ef4ffbfe0df030837b65d7fccfe1abd6549579
https://bscscan.com/token/0xE40255C5d7fa7ceEc5120408C78C787CECB4cfdb
=> add ERC20 and BEP20 SWG

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/chads-vc/
=> add ERC20 CHADS

services/markets/coinmarketcap/mapping.go
Reference:
https://coinmarketcap.com/currencies/swirge/
https://www.coingecko.com/en/coins/swirge
=> Add Swirge (SWGb) BEP20

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/thugs-finance/
=> add BEP20 THUGS

services/markets/coinmarketcap/mapping.go
https://blog.sharering.network/sharering-smart-contract-upgrade/
old contract: https://etherscan.io/token/0xee5fe244406f35d9b4ddb488a64d51456630befc
new contract: https://etherscan.io/token/0xd98f75b1a3261dab9eed4956c93f33749027a964
=> add ERC20 SHR

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/vox-finance/
https://etherscan.io/token/0x12D102F06da35cC0111EB58017fd2Cd28537d0e1
https://bscscan.com/address/0xc227f8eecc481a8e8baa30a4754b109b81c4dfa4
=> add ERC20 and BEP20 VOX

services/markets/coinmarketcap/mapping.go
edit ERC20 GPYX to new contract 0x3e3cda3218212503883c79f6d2feef29e6bbb87d
add BEP20 UNFI https://coinmarketcap.com/currencies/unifi-protocol-dao/
=> edit ERC20 GPYX, add BEP20 UNFI

services/markets/coinmarketcap/mapping.go
Add price for Polkadot BEP2 https://explorer.binance.org/asset/DOT-64C
=> add BEP2 DOT-64C

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/order-of-the-black-rose/
ERC20: https://etherscan.io/token/0x595643D83B35df38E29058976C04000AcFA31570
BEP20: https://bscscan.com/token/0xe49ed1B44117BB7379c1506cf5815aE33089e1A7
=> add ERC20/BEP20 OBR

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/atari-token/
=> add ERC20 ATRI

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/blink/markets/
https://bscscan.com/token/0x63870a18b6e42b01ef1ad8a2302ef50b7132054f
=> add BEP20 Blink

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/cat-token/
https://etherscan.io/token/0x56015bbe3c01fe05bc30a8a9a9fd9a88917e7db3
=> add ERC20 CAT

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/vai/
=> add BEP20 VAI

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/keep3rv1/
https://etherscan.io/token/0x1ceb5cb57c4d4e2b2433641b95dd330a33185a44
=> add ERC20 KP3R

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/lattice-token/
=> add ERC20 LTX

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/rake-finance/
=> add ERC20 RAK

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/klever/
https://tronscan.org/#/token20/TVj7RNVHy6thbM7BWdSe9G6gXwKhjhdNZS
=> add TRC20 KLV

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/unfederalreserve/
=> add ERC20 ERSDL

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/free-coin/
=> add BEP20 TRC10 FREE

services/markets/coinmarketcap/mapping.go
https://bscscan.com/token/0x3d6545b08693dae087e957cb1180ee38b9e3c25e
=> add BEP20 ETC

services/markets/coinmarketcap/mapping.go
https://explorer.binance.org/asset/ETC-758
=> add BEP2 ETC

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/phoneum/
=> add TRC10 PHT

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/beefy-finance/
=> add BEP20 BIFI

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/yvs-finance/
=> add ERC20 YVS

services/markets/coinmarketcap/mapping.go
https://explorer.binance.org/asset/ZEC-93E
=> add BEP2 ZEC

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/reef/
=> add BEP20 REEF

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/reef/
=> add ERC20 REEF

services/markets/coinmarketcap/mapping.go
https://explorer.binance.org/asset/DAI-D75
=> add BEP2 DAI

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/julswap
=> add BEP20 JULD

services/markets/coinmarketcap/mapping.go
KIN 
https://explorer.solana.com/address/kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6
USDC
https://explorer.solana.com/address/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
=> add SPL KIN and USDC

services/markets/coinmarketcap/mapping.go
https://explorer.binance.org/asset/EOS-CDD
=> add BEP2 EOS

services/markets/coinmarketcap/mapping.go
Hi, my name is Stephanus im part of Tokoin.
In this email i want to provide a file related to the token swapping that has been done by the Tokoin team.
And there is something I want to ask, namely the Tokoin logo on the Trust wallet is still empty, there is no logo yet, because now we already change our smart contract .
This is our old contract address: 0x0c963a1b52eb97c5e457c7d76696f8b95c3087ed
and this is our new contract address: 0xa0F0546Eb5E3eE7e8cfC5DA12e5949F3AE622675
=> edit ERC20 TOKO

services/markets/coinmarketcap/mapping.go
https://explorer.binance.org/asset/INJ-FAE
=> add BEP2 INJ

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/bitcoin-standard-hashrate-token/
=> add BEP20 BTCST

services/markets/coinmarketcap/mapping.go
https://etherscan.io/address/0x3155ba85d5f96b2d030a4966af206230e46849cb
https://coinmarketcap.com/currencies/thorchain/
=> add_ERC20_RUNE

services/markets/coinmarketcap/mapping.go
https://blog.chromia.com/announcement-chr-erc-20-token-fork/
https://blog.chromia.com/migration-to-new-erc-20-token-contract-is/
=> edit ERC20 CHR

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/hard-protocol/
https://coinmarketcap.com/currencies/usdx-kava/markets/
=> add KAVA HARD+USDX

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/frontier/
https://etherscan.io/token/0xf8C3527CC04340b208C854E985240c02F7B7793f
https://bscscan.com/token/0x928e55daB735aa8260AF3cEDadA18B5f70C72f1b
=> add ERC20+BEP20 FRONT

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/torn/
https://etherscan.io/token/0x77777feddddffc19ff86db637967013e6c6a116c
=> add ERC20 TORN

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/smartkey/
=> add ERC20 SKEY

services/markets/coinmarketcap/mapping.go
https://medium.com/perlin-network/perl-contract-and-infrastructure-upgrade-dc810a269f6
old: https://etherscan.io/token/0xb5a73f5fc8bbdbce59bfd01ca8d35062e0dad801
new: https://etherscan.io/token/0xeca82185adce47f39c684352b0439f030f860318
https://coinmarketcap.com/currencies/perlin/
=> edit ERC20 PERL

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/staysbase/
=> add BEP20 SBS

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/band-protocol/
https://explorer.binance.org/asset/BAND-34B
=> add BEP2 BAND

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/coti/
https://etherscan.io/address/0xddb3422497e61e13543bea06989c0789117555c5
=> Add COTI ERC20

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/wise/
https://etherscan.io/address/0x66a0f676479cee1d7373f3dc2e2952778bff5bd6
=> add_ERC20_WISE

services/markets/coinmarketcap/mapping.go
https://bscscan.com/address/0xc5137e8e017799e71a65e0cfe3f340d719af17d3
=> add_BEP20_ETHb

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/helmet-insure/
https://bscscan.com/token/0x948d2a81086a075b3130bac19e4c6dee1d2e3fe8
=> add_BEP20_HELMET

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/elrond-egld/
https://bscscan.com/token/0xbf7c81fff98bbe61b40ed186e4afd6ddd01337fe
=> add_BEP20_EGLD

services/markets/coinmarketcap/mapping.go
mTSLA
https://www.bscscan.com/token/0xF215A127A196e3988C09d052e16BcFD365Cd7AA3
mAMZN
https://www.bscscan.com/token/0x3947B992DC0147D2D89dF0392213781b04B25075
mNFLX
https://www.bscscan.com/token/0xa04F060077D90Fe2647B61e4dA4aD1F97d6649dc
mGOOGL
https://www.bscscan.com/token/0x62D71B23bF15218C7d2D7E48DBbD9e9c650B173f
UST
https://www.bscscan.com/token/0x23396cF899Ca06c4472205fC903bDB4de249D6fC
=> add_BEP20_MirrorAssets

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/kebab-token/
https://bscscan.com/token/0x7979f6c54eba05e18ded44c4f986f49a5de551c2
=> add_BEP20_KEBAB

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/hedget/
https://etherscan.io/token/0x7968bc6a03017eA2de509AAA816F163Db0f35148
https://bscscan.com/token/0xc7d8d35eba58a0935ff2d5a33df105dd9f071731
=> add_ERC20+BEP20_HGET

services/assets/client.go
Based on https://github.com/trustwallet/assets/pull/5461 changes
=> Consolidate usage of description into one field in coin info

api/api_test.go, api/endpoint/charts.go, api/endpoint/info.go, api/endpoint/tickers.go, cmd/api/main.go, go.sum, services/assets/client.go, services/assets/client_test.go, services/controllers/charts/base.go, services/controllers/charts/base_test.go, services/controllers/charts/models.go, services/controllers/charts/normalization.go, services/controllers/info/base.go, services/controllers/info/base_test.go, services/controllers/info/models.go, services/controllers/info/normalization.go, services/controllers/models.go, services/controllers/tickers/base_test.go, services/controllers/tickers/normalization.go, services/controllers/tickers/normalization_test.go, services/controllers/tickers/tickers_test.go, services/markets/coingecko/charts.go, services/markets/coingecko/charts_test.go, services/markets/coinmarketcap/charts.go, services/markets/coinmarketcap/charts_test.go, services/markets/markets.go
Reverts trustwallet/watchmarket#358
=> Revert "Optimize codebase"

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/safepal/
=> add_BEP20_SFP

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/yvs-finance/
=> add_BEP20_YVS

services/markets/coinmarketcap/mapping.go
BEP2: https://explorer.binance.org/asset/AAVE-8FA
BEP20: https://bscscan.com/address/0xfb6115445bff7b52feb98650c87f44907e58f802
=> Add AAVE (BEP2 and BEP20) pricing

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/auto/
https://bscscan.com/token/0xa184088a740c695e156f91f5cc086a06bb78b827
=> add_BEP20_AUTO

services/markets/coinmarketcap/mapping.go
Added BETH, USDC and ONT
BETH: https://bscscan.com/address/0x250632378E573c6Be1AC2f97Fcdf00515d0Aa91B
ONT: https://bscscan.com/address/0xFd7B3A77848f1C2D67E05E54d78d174a0C850335
USDC: https://bscscan.com/address/0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d
=> add_BEP20_Binance-Pegged

services/markets/coinmarketcap/mapping.go
https://etherscan.io/token/0xac0104cca91d167873b8601d2e71eb3d4d8c33e0
https://coinmarketcap.com/currencies/crowns/
=> add_ERC20_CWS

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/billionhappiness/
=> Add BHC BEP20 pricing

api/api_test.go, api/endpoint/tickers.go, db/db.go, db/postgres/ticker.go, pkg/watchmarket/models.go, services/controllers/charts/base.go, services/controllers/charts/base_test.go, services/controllers/controllers.go, services/controllers/info/base.go, services/controllers/info/base_test.go, services/controllers/tickers/base.go, services/controllers/tickers/base_test.go, services/controllers/tickers/normalization.go, services/controllers/tickers/normalization_test.go, services/controllers/tickers/rates.go, services/controllers/tickers/tickers.go, services/controllers/tickers/tickers_test.go, services/worker/memory_test.go, tests/integration/db_test/ticker_test.go
Reverts trustwallet/watchmarket#378
=> Revert "Clean codebase"

services/markets/coinmarketcap/mapping.go
https://explorer.binance.org/asset/MATIC-84A
=> Add MATIC BEP2 pricing

services/markets/coinmarketcap/mapping.go
https://bscscan.com/token/0x37109a51e712471bd2c72d8d70718627e7ff0032
=> Add Swapcoinz SPAZ BEP20 pricing

services/markets/coinmarketcap/mapping.go
https://bscscan.com/token/0x111111111117dc0aa78b770fa6a738034120c302
https://1inch-exchange.medium.com/1inch-network-expands-to-binance-smart-chain-1a718a154034
=> add_BEP20_1INCH

services/markets/coinmarketcap/mapping.go
https://etherscan.io/token/0x0ef3b2024ae079e6dbc2b37435ce30d2731f0101
https://coinmarketcap.com/currencies/unifi-defi/
=> add_ERC20_UNIFI

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/ditto/
https://bscscan.com/address/0x233d91a0713155003fc4dce0afa871b508b3b715
=> Add DITTO (BEP20) pricing

services/markets/coinmarketcap/mapping.go
https://bscscan.com/token/0x67ee3cb086f8a16f34bee3ca72fad36f7db929e2
https://coinmarketcap.com/currencies/dodo/
=> add_BEP20_DODO

services/markets/coinmarketcap/mapping.go
add 
XRP BEP2: https://explorer.binance.org/asset/XRP-BF2
BKBT BEP2: https://explorer.binance.org/asset/BKBT-3A6
=> add_BEP2_XRP+BKBT

services/markets/coinmarketcap/mapping.go
Change from 0x82b0E50478eeaFde392D45D1259Ed1071B6fDa81 to 0xef6344de1fcfC5F48c30234C16c1389e8CdC572C
Reference: https://encrypgen.com/the-big-dna-token-swap/
=> Update DNA (ERC20) pricing

services/markets/coinmarketcap/mapping.go
https://github.com/trustwallet/assets/pull/5788
=> add_BEP20_RAMP

services/markets/coinmarketcap/mapping.go
https://bscscan.com/token/0x947950bcc74888a40ffa2593c5798f11fc9124c4
=> add_BEP20_SUSHI

services/markets/coinmarketcap/mapping.go
https://explorer.binance.org/asset/AWC-986
https://coinmarketcap.com/currencies/atomic-wallet-coin/
=> add_BEP2_AWC

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/jetfuel-finance/
https://www.coingecko.com/en/coins/jetfuel-finance
=> Add Jetfuel Finance (FUEL) BEP20 pricing

services/markets/coinmarketcap/mapping.go
https://github.com/trustwallet/assets/pull/5837
=> add_BEP2_SUSHI

services/markets/coinmarketcap/mapping.go
https://github.com/trustwallet/assets/pull/5838
=> add_BEP2-BEP20_COCOS

services/markets/coinmarketcap/mapping.go
https://explorer.binance.org/asset/SXP-CCC
=> add_BEP2_SXP

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/shadows/
https://www.coingecko.com/en/coins/shadows/
=> Add Shadows (DOWS) ERC20 pricing

services/markets/coinmarketcap/mapping.go
https://etherscan.io/token/0xd478161c952357f05f0292b56012cd8457f1cfbf
https://coinmarketcap.com/currencies/polkamarkets/
=> add_ERC20_POLK

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/spartan-protocol/
https://www.coingecko.com/en/coins/spartan-protocol-token
=> Add Spartan Protocol Token (SPARTA) BEP20 pricing

api/api.go, api/endpoint/rates.go, db/db.go, db/postgres/rate.go, services/controllers/charts/base_test.go, services/controllers/controllers.go, services/controllers/info/base_test.go, services/controllers/models.go, services/controllers/rates/base.go, services/controllers/tickers/base_test.go, services/worker/memory_test.go
=> Add fiat rates endpoint

services/markets/coinmarketcap/mapping.go
https://github.com/trustwallet/assets/pull/5892
=> edit_ERC20_PAID

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/dos-network/
https://www.coingecko.com/en/coins/dos-network
=> Add DOS Network (DOS) BEP2 and BEP20 pricing

services/markets/coinmarketcap/mapping.go
https://etherscan.io/token/0x5d762f76b9e91f71cc4f94391bdfe6333db8519c
https://coinmarketcap.com/currencies/iyf-finance/
=> add_ERC20_IYF

services/markets/coinmarketcap/mapping.go
https://explorer.binance.org/asset/IRIS-D88
https://coinmarketcap.com/currencies/irisnet/
=> add_BEP2_IRIS

services/markets/coinmarketcap/mapping.go
added several missing BEP2 token price
=> add_BEP2_missing_price_3/16

services/markets/coinmarketcap/mapping.go
added several missing assets
BFI
BDO
bwJUP
arNXM
EWTB
=> add_ERC20_BEP20_missing

services/markets/coinmarketcap/mapping.go
https://explorer.binance.org/asset/CAKE-435
https://coinmarketcap.com/currencies/pancakeswap/
https://www.coingecko.com/en/coins/pancakeswap
=> Add CAKE-435 BEP2 pricing

services/markets/coinmarketcap/mapping.go
https://explorer.binance.org/asset/BOLT-4C6
https://coinmarketcap.com/currencies/bolt/
https://www.coingecko.com/en/coins/bolt
=> Add BOLT-4C6 BEP2 pricing

services/markets/coinmarketcap/mapping.go
Contract migration: https://medium.com/tellor/trb-migration-fd8ebe320b02
From `0x0Ba45A8b5d5575935B8158a88C631E9F9C95a2e5` to `0x88dF592F8eb5D7Bd38bFeF7dEb0fBc02cf3778a0`
=> Update Tellor (TRB) ERC20 pricing

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/ecomi/
https://www.coingecko.com/en/coins/ecomi
=> Add Ecomi (OMI) GO20 pricing

services/markets/coinmarketcap/mapping.go
https://bscscan.com/token/0xcc42724c6683b7e57334c4e856f4c9965ed682bd
https://coinmarketcap.com/currencies/polygon/
=> Add MATIC (BEP20)

cmd/api/main.go, services/controllers/charts/base.go, services/controllers/charts/base_test.go, services/controllers/info/base.go, services/controllers/info/base_test.go, services/controllers/rates/base.go, services/controllers/tickers/base.go, services/controllers/tickers/base_test.go, services/controllers/tickers/rates_test.go, services/controllers/tickers/tickers_test.go
Reverts trustwallet/watchmarket#425
=> Revert "Remove database requests"

services/markets/coinmarketcap/mapping.go
https://coinmarketcap.com/currencies/safemars/
https://www.coingecko.com/en/coins/safemars
https://bscscan.com/token/0x3ad9594151886ce8538c1ff615efa2385a8c3a88
=> Add Safemars (SAFEMARS) BEP20

services/markets/coinmarketcap/mapping.go
https://www.coingecko.com/en/coins/morpheus-labs
https://coinmarketcap.com/currencies/morpheus-labs/
https://www.coingecko.com/en/coins/morpheus-labs
=> Add MITX BEP2 pricing

services/markets/coinmarketcap/mapping.go
https://explorer.binance.org/asset/PHB-2DF
https://coinmarketcap.com/currencies/phoenix-global/
https://www.coingecko.com/en/coins/phoenix-global
=> Add Red Pulse Phoenix Binance (PHB-2DF) BEP2
