trustwallet/watchmarket

- Makefile
1. Removes redundant build directives (that were leftover from the Blockatlas migration)
1. Moves `all` directive to the top - didn't work for me when defined on the bottom
> Cleans up Makefile

- market/rate/coingecko/coingecko.go
- market/rate/coingecko/coingecko_test.go
Some coins in _CoinGecko_ have `null` or 0 rates (see data in #21 ). This sets the Watchmarket rate for such coins to zero.
@vikmeup to confirm whether a rate of 0 is actually the correct solution here.
> Fixes CoinGecko handling of coins  with null or 0 prices (#21)

- market/market.go
- market/rates.go
- storage/market.go
- storage/storage.go
This solves multiple problems:
1. fixed error reporting: currently when we decide to skip saving a record due to priority we log an `ERROR`. This is wrong
1. noisy logs: currently for each record we skip due to its priority we create a log statement. That's thousands of log statements. This cleans these log statements up
Don't log errors for skipped records and change the contract to provide information about how many records were skipped and why.
`make start` and the new log output is much more crisp (prior there were thousands of `ERROR` logs):
```
INFO[0016] Done fetching latest rates                    numFetchedRates=6863 provider=coingecko results="map[SkippedLowPriority:4 SkippedLowPriorityOrOutdated:879 StorageFailure:95 Success:5885]"
INFO[0026] Market data result …
```
> Improves market observer logging

- README.md
- api/marketdata.go
- azure-pipelines.yml
- go.mod
- pkg/watchmarket/errors.go
- redis/hmap.go
- redis/redis.go
- storage/storage.go
We currently are not consistently transparent to users as to why their requests fail. As an example, a request for a coin named "i do not exist" will result in a HTTP 500 error, leading clients to think that this was an internal server error.
This should be a HTTP 404 to signal to clients that there is no record for a coin called "i do not exist".
We currently use a thin layer around the Go Redis client from [Blockatlas](github.com/trustwallet/blockatlas/pkg/storage/redis). This implementation is flawed as it loses granularity around NotFoundErrors.
Instead of patching Blockatlas' implementation and using the Blockatlas error definitions this change is moving the Blockatlas wrapper into Watchmarket while improving the error handling. Also using new Watchmarket errors definitions.
Further …
> Properly implements HTTP 404 status codes (Fixes #23)

- cmd/market_api/main.go
- cmd/market_observer/main.go
- cmd/swagger_api/main.go
- internal/init.go
Rationale: app bootstrap is currently highly coupled to specific implementations of the app server, web framework, cache implementation. This prevents from bootstrapping with any alternative implementations of these. We will want to provide alternative implementations of server and cache for instance for functional testing.
Highlights:
* `market_observer` bootstrap invokes `internal.InitAPIWithRedis` despite not serving an API - refactored to instead leverage a new `internal.InitRedis` function
* swagger API and market API use `internal.InitAPI` and `internal.InitAPIWithRedis` apis. These are mostly equivalent/redundant. Introducing a `internal.InitEngine` instead to share code
* swapper API has a dependency on `marketdata.go` to serve app root which is unnecessary
* swagger API "GET /" …
> Separates concerns in app bootstrap

- Makefile
- README.md
- azure-pipelines.yml
See https://codecov.io/gh/trustwallet/watchmarket/branch/feature%2Fcoverage for an example.
Rationale:
* go native coverage reports are not great to read
* increases emphasis on test coverage/code quality
> Integrates with codecov.io

- .gitignore
- Makefile
- api/marketdata.go
- go.mod
- internal/init.go
- storage/market.go
- storage/market_test.go
- storage/storage.go
* Fixes swallowing of errors of `SaveTicker` and `SaveRates` API
* Adds unit tests for Market using testify/mock and mockery.
* Creates HTML test coverage report
market.go test coverage:
before: 0%
after: 100%
> Fixed: `SaveTicker` and `SaveRates` APIs swallow errors

- .codecov.yml
- .gitignore
- Makefile
- api/api.go
- api/api_test.go
- api/marketdata.go
- cmd/market_api/main.go
- go.mod
To support these functional tests this change also slightly refactors API bootstrap to support testing scenarios.
Uses:
* [Miniredis](https://github.com/alicebob/miniredis) to provide the tests with a Redis instance
* [httptest.Server](https://golang.org/pkg/net/http/httptest/) as test server
Also:
* Fixed a bug where we would signal HTTP 500 status code when the client posts bad JSON (fixed to 400)
* Fixed not logging when coins in the payload are not supported
> Tests "/v1/market/ticker" API

- Makefile
- api/api_test.go
- cmd/market_observer/main.go
- market/market.go
- market/market/cmc/cmc.go
- market/market/coingecko/coingecko.go
- market/market/compound/compound.go
- market/market/dex/dex.go
- market/market/marketprovider.go
- market/market_test.go
- market/rate/cmc/cmc.go
- market/rate/coingecko/coingecko.go
- market/rate/compound/compound.go
- market/rate/fixer/fixer.go
- market/rate/rateprovider.go
- market/rates.go
- market/worker.go
- storage/market_test.go
* Adds a basic functional test for the market observer using [Miniredis](https://github.com/alicebob/miniredis)
* Refactors observer initializer:
* to take a list of providers from its consumer
* return a `Cron` object that can be started/stopped by the consumer
* Renames conflicting `Provider` interfaces to support mock generation with mockery
* Moves generated mocks into according subdirectories to avoid import cycles
> Tests Market Observer

- cmd/market_observer/main.go
- internal/shutdown.go
Small fix for [#37 ](https://github.com/trustwallet/watchmarket/issues/37).
Further improvement ideas:
- Allow the logs to be more verbose or specific (adding [ComponentName] before level would help to differentiate shutdown logs for example.
- Ability to start/shutdown component selectively
- Migrate from makefile to cli command (?)
> Fix observer jobs to shutdown gracefully

- Makefile
- api/api.go
- api/api_test.go
- api/marketdata.go
- cmd/market_api/main.go
- go.mod
- market/chart/chartprovider.go
- market/chart/cmc/cmc.go
- market/chart/coingecko/coingecko.go
- market/charts.go
- services/assets/info.go
- services/assets/info_test.go
Coininfo API doesn't implement HTTP Not Found and fails such requests with HTTP Internal Server Error instead.
The HTTP client used does not expose said errors.
Changes:
* Coininfo API now returns HTTP 404 when coin is not available
* Coininfo API does some more input validation and returns HTTP 400 when validations fail 
* Uses `resty` as HTTP client
* Removes HTTP level caching - potentially problematic but  #47 introduces app layer caching
* Introduces functional test for Coininfo API
Also adding the Codecov token to `.codecov.yml`. This should not be required when using Azure Pipelines and public repositories but it sometimes works and sometimes fails. Improvement would be to move the token to the Azure environment. I see no security concern with adding this here.
Ran `newman` tests …
> Fixed: Coin info API doesn't properly implement HTTP protocol (Fixes #44)

- api/api_test.go
- api/marketdata.go
- market/charts.go
* Fixed: Charts API does not properly implement 404 status code
* Improves error messages when invalid coin/start times are provided
Covers charts in functional tests.
* `make test`
* Ran newman tests
> Fixed: Charts API does not properly implement 404 status code

- market/charts.go
Cmc does not handle such amount of requests on production with their limit. Even caching and proxy does not help with it. So I want to change charts provider priority temporary until we will solve the cmc issue
> Change charts provider to coingecko

- market/market.go
- market/market_test.go
- market/rates.go
- market/worker.go
* it is not clear why we would have cron-level exponential backoff - by definition crons retry after the specified interval
* retries were based on the contract of any `error` causing a retry. This is wrong as some errors may not be retryable
* Retrying should arguably be on another layer e.g. add retries to explorer API clients if the API returns HTTP5XX
* the retry contract of returning errors was not cleanly implemented - some errors were swallowed and some were without a sensical pattern
> Removes cron-level retries

- api/api_test.go
- api/marketdata.go
Remove hardcoded TWT token
Change api behavior, so we will return chart.info even if we will not have chart for it
> Remove hardcoded token from marketdata

- market/clients/coingecko/cache.go
CG platform can be equal to symbol, like BNB bnb, what breaks the logic.
> Solve issue with CG

- services/markets/coinmarketcap/mapping.go
used same source as CAKE since it is 1:1 with SYRUP
https://coinmarketcap.com/currencies/pancakeswap/
> added BEP20 SYRUP

- services/markets/coinmarketcap/mapping.go
I checked CMC, TRC10 price is being tracked: https://coinmarketcap.com/currencies/lovehearts/
https://tronscan.org/#/token/1000451
But CG tracks the TRC20 toke: https://www.coingecko.com/en/coins/lovehearts
https://tronscan.org/#/token20/TGbhcodQ1jRWB3ZywmfwsRTh4rwbiL2mzh
Adding the TRC20 token contract.
> adding TRC20 LVH

- services/markets/coinmarketcap/mapping.go
LEND has migrated to AAVE at a rate of 100 LEND per 1 AAVE.
https://medium.com/aave/migration-and-staking-101-fe8fda3e2a30
https://coinmarketcap.com/currencies/aave-new/
https://etherscan.io/address/0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9
> adding ERC20 AAVE-NEW

- services/markets/coinmarketcap/mapping.go
Added the following BEP20 assets.
[MKR](https://bscscan.com/address/0x5f0Da599BB2ccCfcf6Fdfd7D81743B6020864350), [COMP](https://bscscan.com/address/0x52CE071Bd9b1C4B00A0b92D298c512478CaD67e8), [ELF](https://bscscan.com/address/0xa3f020a5C92e15be13CAF0Ee5C95cF79585EeCC9), [TCT](https://bscscan.com/address/0xCA0a9Df6a8cAD800046C1DDc5755810718b65C44), [IOTX](https://bscscan.com/address/0x9678E42ceBEb63F23197D726B29b1CB20d0064E5), [BEL](https://bscscan.com/address/0x8443f091997f06a61670B735ED92734F5628692F)
Source:
https://www.binance.com/en/support/announcement/ca94b7a6751b4b2b9451f7a3ceb8dbce
> adding BEP20 assets 10/12

- services/markets/coinmarketcap/mapping.go
Seele has just completed a chain swap where the contract address migrated from 0xb1eef147028e9f480dbc5ccaa3277d417d1b85f0 to 0xb1e93236ab6073fdac58ada5564897177d4bcc43
New contract: https://etherscan.io/address/0xb1e93236ab6073fdac58ada5564897177d4bcc43
> update ERC20 SEELE

- go.mod
- go.sum
- services/markets/binancedex/tickers.go
- services/markets/coingecko/mocks/tickers.json
- services/markets/coingecko/tickers.go
Changes:
1. update golibs/coin package to remove legacy bsc
2. sort coins in `getCoinBySymbol`
> Fix unstable tickers_test.go

- services/markets/coinmarketcap/mapping.go
To avoid confusion, the pricing data for ERD should be removed.
Example: https://community.trustwallet.com/t/my-wallet-won-t-show-elrond-erc20-value/103661/34
> Remove Elrond [ERD] (ERC20)

- services/markets/coinmarketcap/mapping.go
Change token_id from 0xdF1D6405df92d981a2fB3ce68F6A03baC6C0E41F to 0xF411903cbC70a74d22900a5DE66A2dda66507255
https://coinmarketcap.com/currencies/verasity/
https://www.coingecko.com/en/coins/verasity
https://twitter.com/verasitytech/status/1359152323411529737
> Update Verasity (VRA) ERC20 pricing

- services/markets/coinmarketcap/mapping.go
https://btcst.medium.com/btcst-to-implement-results-of-stp-4-1-10-redenomination-the-week-of-march-15-872c9ea3d5b7
https://bscscan.com/address/0x78650b139471520656b9e7aa7a5e9276814a38e9
https://coinmarketcap.com/currencies/btc-standard-hashrate-token/
https://www.coingecko.com/en/coins/btc-standard-hashrate-token
> Update Bitcoin Standard Hashrate Token (BTCST) BEP20 pricing
